CREATE TABLE IF NOT EXISTS cars (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    inventory INT NOT NULL DEFAULT 0,
    daily_fee DECIMAL(10, 2) NOT NULL
);